// src/lib/departments.js
//
// The canonical list of departments a student can be in. 380 entries.
//
// WHY A LIST AND NOT FREE TEXT. The live data before this file existed held
// NINETEEN distinct values for about eight real departments — "Artificial
// Intelligence & Machine Learning (AI & ML)", "Artificial Intelligence and
// Machine Learning" and "AI" were three spellings of one course, and nothing
// downstream could tell they were the same. Every filter, every per-department
// count and every leaderboard grouping silently split them apart. Choosing from
// a fixed list is what stops that recurring; migration 010 collapsed the
// spellings that already existed.
//
// STORED AS FULL NAMES, not codes. The old dropdown stored "CSE"/"IT"/"ADS",
// which read as nothing on a leaderboard and collided with the free text that
// bulk imports were writing anyway. The string in the database is the string on
// screen.
//
// GROUPS ARE PRESENTATION ONLY. Nothing keys off them — they exist so a list
// this long stays navigable. The value submitted and stored is always the plain
// department name.
//
// KEEP IN SYNC WITH backend/utils/departments.js. The API and the SPA are
// separate deployments with no shared package between them, so the list is
// duplicated deliberately; change both in the same commit.

/** Presentation grouping for the picker. Order matters; it is the display order. */
export const DEPARTMENT_GROUPS = [
  {
    label: "Engineering & Technology",
    items: [
      "Aeronautical Engineering",
      "Aerospace Engineering",
      "Agricultural Engineering",
      "Automobile Engineering",
      "Biomedical Engineering",
      "Biotechnology",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science and Engineering",
      "Computer Science and Business Systems",
      "Computer Science and Engineering (Artificial Intelligence)",
      "Computer Science and Engineering (Artificial Intelligence and Machine Learning)",
      "Computer Science and Engineering (Cyber Security)",
      "Computer Science and Engineering (Data Science)",
      "Computer Science and Engineering (Internet of Things)",
      "Computer Science and Engineering (Information Security)",
      "Computer Science and Engineering (Blockchain Technology)",
      "Computer Science and Engineering (Cloud Computing)",
      "Electrical and Electronics Engineering",
      "Electronics and Communication Engineering",
      "Electronics and Instrumentation Engineering",
      "Electronics and Telecommunication Engineering",
      "Environmental Engineering",
      "Food Technology",
      "Food Processing Technology",
      "Industrial Biotechnology",
      "Industrial Engineering",
      "Information Technology",
      "Instrumentation and Control Engineering",
      "Marine Engineering",
      "Mechanical Engineering",
      "Mechatronics Engineering",
      "Metallurgical and Materials Engineering",
      "Mining Engineering",
      "Naval Architecture and Ocean Engineering",
      "Petroleum Engineering",
      "Pharmaceutical Engineering",
      "Plastic Technology",
      "Production Engineering",
      "Robotics and Automation Engineering",
      "Safety and Fire Engineering",
      "Textile Technology",
      "Textile Engineering",
      "Fashion Technology",
      "Printing Technology",
      "Leather Technology",
      "Ceramic Technology",
      "Polymer Technology",
      "Rubber Technology",
      "Industrial Engineering and Management",
      "Manufacturing Engineering",
      "Manufacturing Science and Engineering",
      "Automobile Engineering and Electric Vehicle Technology",
      "Electric Vehicle Technology",
      "Renewable Energy Engineering",
      "Energy Engineering",
      "Nuclear Engineering",
      "Engineering Physics",
      "Engineering Design",
      "Mechatronics and Robotics Engineering",
      "Artificial Intelligence and Data Science",
      "Artificial Intelligence and Machine Learning",
      "Artificial Intelligence and Robotics",
      "Data Science and Engineering",
      "Data Engineering",
      "Computer Engineering",
      "Computer Technology",
      "Information Science and Engineering",
      "Information and Communication Technology",
      "Software Engineering",
      "Software Systems Engineering",
      "Cyber Security Engineering",
      "Internet of Things Engineering",
      "Cloud Technology and Information Security",
      "Blockchain Engineering",
      "Computer Science and Medical Engineering",
      "Computer Science and Design",
      "Computer Science and Engineering (IoT)",
      "Computer Science and Engineering (Gaming Technology)",
      "Computer Science and Engineering (Quantum Computing)",
      "Computer Science and Engineering (FinTech)",
      "Computer Science and Engineering (DevOps)",
      "Computer Science and Engineering (Full Stack Development)",
      "Computer Science and Engineering (AI and Robotics)",
      "Electronics and Computer Engineering",
      "Electronics and Communication Engineering (Advanced Communication Technology)",
      "Electronics and VLSI Design",
      "VLSI Design and Technology",
      "Microelectronics and VLSI Engineering",
      "Embedded Systems Engineering",
      "Communication Systems Engineering",
      "Telecommunication Engineering",
      "Biomedical Instrumentation Engineering",
      "Medical Electronics Engineering",
      "Electrical and Computer Engineering",
      "Power Engineering",
      "Power Electronics and Drives",
      "Electrical and Instrumentation Engineering",
      "Control Systems Engineering",
      "Mechatronics and Industrial Automation",
      "Robotics Engineering",
      "Automation and Robotics Engineering",
      "Industrial Automation Engineering",
      "Mechanical and Automation Engineering",
      "Mechanical Engineering (Manufacturing)",
      "Mechanical Engineering (Automobile)",
      "Mechanical Engineering (Electric Vehicles)",
      "Mechanical Engineering (Robotics)",
      "Civil and Structural Engineering",
      "Structural Engineering",
      "Construction Engineering and Management",
      "Construction Technology",
      "Infrastructure Engineering",
      "Geotechnical Engineering",
      "Transportation Engineering",
      "Water Resources Engineering",
      "Environmental Engineering and Management",
      "Coastal Engineering",
      "Ocean Engineering",
      "Petroleum Technology",
      "Petrochemical Engineering",
      "Chemical Technology",
      "Polymer Engineering",
      "Biochemical Engineering",
      "Biotechnology Engineering",
      "Genetic Engineering",
      "Bioinformatics Engineering",
      "Biomedical Instrumentation",
      "Agricultural and Irrigation Engineering",
      "Agricultural Technology",
      "Food Engineering",
      "Dairy Technology",
      "Dairy Engineering",
      "Fisheries Engineering",
      "Aquaculture Engineering",
      "Marine Technology",
      "Ocean Technology",
      "Port and Harbour Engineering",
      "Mining Engineering and Technology",
      "Metallurgy Engineering",
      "Materials Engineering",
      "Materials Science and Engineering",
      "Ceramic Engineering",
      "Glass Technology",
      "Textile Chemistry",
      "Textile Engineering and Technology",
      "Apparel Technology",
      "Fashion Technology and Management",
      "Footwear Technology",
      "Handloom Technology",
      "Jute Technology",
      "Paper Technology",
      "Printing and Packaging Technology",
      "Packaging Technology",
      "Pharmaceutical Technology",
      "Pharmaceutical Engineering and Technology",
      "Biomedical Engineering and Biotechnology",
      "Medical Biotechnology",
      "Nanotechnology Engineering",
      "Nanoscience and Technology",
      "Genetic and Bioengineering",
      "Computational Biology",
      "Biosystems Engineering",
      "Environmental Biotechnology",
      "Industrial Biotechnology Engineering",
      "Agricultural Biotechnology",
      "Food Biotechnology",
      "Marine Biotechnology",
      "Bioenergy Engineering",
      "Renewable Energy Technology",
      "Solar Energy Engineering",
      "Wind Energy Engineering",
      "Energy and Environmental Engineering",
      "Nuclear Engineering and Technology",
      "Nuclear Science and Engineering",
      "Space Technology Engineering",
      "Avionics Engineering",
      "Aircraft Maintenance Engineering",
      "Aerospace Engineering and Technology",
      "Aeronautical Engineering and Technology",
      "Aircraft Engineering",
      "Aviation Engineering",
      "Automobile Technology",
      "Automotive Engineering",
      "Electric and Autonomous Vehicle Engineering",
      "Automotive Electronics",
      "Transportation Engineering and Technology",
      "Railway Engineering",
      "Railway Systems Engineering",
      "Railway Infrastructure Engineering",
      "Naval Architecture",
      "Ship Building Engineering",
      "Marine Engineering and Technology",
      "Offshore Engineering",
      "Subsea Engineering",
      "Petroleum and Gas Engineering",
      "Oil and Gas Engineering",
      "Mining Machinery Engineering",
      "Fire and Safety Engineering",
      "Disaster Management Engineering",
      "Safety Engineering",
      "Industrial Safety Engineering",
      "Engineering Mathematics",
      "Engineering Chemistry",
      "Engineering Geology",
      "Computational Engineering",
      "Systems Engineering",
      "Systems and Control Engineering",
      "Operations Engineering",
      "Logistics Engineering",
      "Supply Chain Engineering",
      "Financial Engineering",
      "Manufacturing Systems Engineering",
      "Production Systems Engineering",
      "Quality Engineering",
      "Reliability Engineering",
      "Mechatronics and Automation",
      "Robotics and Artificial Intelligence",
      "Artificial Intelligence Engineering",
      "Machine Learning Engineering",
      "Data Analytics Engineering",
      "Big Data Engineering",
      "Cloud Computing Engineering",
      "DevOps Engineering",
      "Cyber Forensics Engineering",
      "Information Security Engineering",
      "Network Engineering",
      "Network and Cyber Security Engineering",
      "Digital Forensics Engineering",
      "Blockchain and Cyber Security Engineering",
      "FinTech Engineering",
      "Quantum Technology Engineering",
      "Quantum Computing Engineering",
      "Human-Computer Interaction Engineering",
      "Computer Graphics Engineering",
      "Game Technology Engineering",
      "Multimedia Technology Engineering",
      "Computer Science and Engineering (Design)",
    ],
  },
  {
    label: "Computer Applications (BCA)",
    items: [
      "BCA – Computer Applications",
      "BCA – Computer Science",
      "BCA – Information Technology",
      "BCA – Software Development",
      "BCA – Data Science",
      "BCA – Data Analytics",
      "BCA – Artificial Intelligence",
      "BCA – Artificial Intelligence and Machine Learning",
      "BCA – Machine Learning",
      "BCA – Cyber Security",
      "BCA – Cloud Computing",
      "BCA – Blockchain Technology",
      "BCA – Internet of Things (IoT)",
      "BCA – Full Stack Development",
      "BCA – Web Development",
      "BCA – Mobile Application Development",
      "BCA – Computer Networking",
      "BCA – Network Security",
      "BCA – Information Security",
      "BCA – Software Engineering",
      "BCA – Game Development",
      "BCA – Multimedia and Animation",
      "BCA – Digital Forensics",
      "BCA – DevOps",
      "BCA – Big Data Analytics",
      "BCA – Business Analytics",
      "BCA – FinTech",
      "BCA – Computer Graphics",
    ],
  },
  {
    label: "Science (BSc)",
    items: [
      "Bachelor of Science in Computer Science (BSc CS)",
      "BSc – Computer Science and Applications",
      "BSc – Information Technology",
      "BSc – Information Systems",
      "BSc – Software Development",
      "BSc – Software Engineering",
      "BSc – Data Science",
      "BSc – Data Analytics",
      "BSc – Artificial Intelligence",
      "BSc – Artificial Intelligence and Machine Learning",
      "BSc – Machine Learning",
      "BSc – Cyber Security",
      "BSc – Cyber Forensics",
      "BSc – Digital Forensics",
      "BSc – Cloud Computing",
      "BSc – Cloud Technology",
      "BSc – Blockchain Technology",
      "BSc – Internet of Things (IoT)",
      "BSc – Big Data Analytics",
      "BSc – Business Analytics",
      "BSc – Computer Networking",
      "BSc – Network Security",
      "BSc – Information Security",
      "BSc – Mobile Computing",
      "BSc – Web Technology",
      "BSc – Web Development",
      "BSc – Full Stack Development",
      "BSc – Game Development",
      "BSc – Computer Graphics",
      "BSc – Multimedia and Animation",
      "BSc – Digital Media",
      "BSc – DevOps",
      "BSc – FinTech",
      "BSc – Computational Science",
      "BSc – Computational Mathematics",
      "BSc – Computer Applications",
      "BSc – Electronics and Computer Science",
      "BSc – Mathematics and Computer Science",
      "BSc – Physics and Computer Science",
      "BSc – Statistics and Computer Science",
      "Bachelor of Science in Mathematics and Computing",
      "Bachelor of Science in Statistics and Data Science",
      "Bachelor of Science in Mathematics and Data Science",
      "Bachelor of Science in Statistics and Analytics",
      "Bachelor of Science in Economics and Data Science",
      "Bachelor of Science in Economics and Analytics",
      "Bachelor of Science in Computational Economics",
      "Bachelor of Science in Computational Statistics",
      "Bachelor of Science in Bioinformatics",
      "Bachelor of Science in Computational Biology",
      "Bachelor of Science in Biotechnology and Bioinformatics",
      "Bachelor of Science in Geoinformatics",
      "Bachelor of Science in Geographic Information Systems (GIS)",
      "Bachelor of Science in Health Informatics",
      "Bachelor of Science in Medical Informatics",
    ],
  },
  {
    label: "Computing & IT degrees",
    items: [
      "Bachelor of Computer Applications (BCA)",
      "Bachelor of Computer Science (BCS)",
      "Bachelor of Computing (BComp)",
      "Bachelor of Information Technology (BIT)",
      "Bachelor of Information Systems (BIS)",
      "Bachelor of Software Engineering (BSE)",
      "Bachelor of Data Science",
      "Bachelor of Artificial Intelligence",
      "Bachelor of Cyber Security",
      "Bachelor of Information Security",
      "Bachelor of Cloud Computing",
      "Bachelor of Computer Engineering",
      "Bachelor of Computing Applications",
      "Bachelor of Computer and Information Science",
      "Bachelor of Digital Technology",
    ],
  },
  {
    label: "Commerce & Management",
    items: [
      "Bachelor of Commerce in Computer Applications (BCom CA)",
      "Bachelor of Commerce in Information Technology",
      "Bachelor of Commerce in Business Analytics",
      "Bachelor of Commerce in E-Commerce",
      "Bachelor of Commerce in FinTech",
      "Bachelor of Commerce in Digital Business",
      "Bachelor of Business Administration in Business Analytics",
      "BBA in Information Technology",
      "BBA in Computer Applications",
      "BBA in Artificial Intelligence",
      "BBA in Data Analytics",
      "BBA in Digital Business",
      "BBA in FinTech",
      "BBA in Digital Marketing and Technology",
      "BBA in Business Intelligence",
      "BBA in Information Systems",
    ],
  },
  {
    label: "Arts",
    items: [
      "Bachelor of Arts in Computer Applications",
      "Bachelor of Arts in Computer Science",
      "Bachelor of Arts in Information Technology",
      "Bachelor of Arts in Digital Technology",
      "Bachelor of Arts in Data Science",
      "Bachelor of Arts in Economics and Data Analytics",
      "Bachelor of Arts in Computational Economics",
      "Bachelor of Arts in Digital Media",
      "Bachelor of Arts in Multimedia and Digital Media",
      "Bachelor of Arts in Animation and Multimedia",
      "Bachelor of Arts in Game Design",
      "Bachelor of Arts in User Experience Design",
      "Bachelor of Arts in Interaction Design",
      "Bachelor of Arts in Digital Design",
      "Bachelor of Arts in Communication and Digital Media",
      "Bachelor of Arts in Journalism and Digital Media",
      "Bachelor of Arts in Media Technology",
      "Bachelor of Arts in Digital Marketing",
      "Bachelor of Arts in Advertising and Digital Media",
    ],
  },
  {
    label: "Design",
    items: [
      "Bachelor of Design in User Experience Design",
      "Bachelor of Design in Interaction Design",
      "Bachelor of Design in Communication Design",
      "Bachelor of Design in Digital Product Design",
      "Bachelor of Design in Game Design",
      "Bachelor of Design in Animation",
      "Bachelor of Design in Multimedia Design",
      "Bachelor of Design in Visual Communication",
      "Bachelor of Design in Digital Experience Design",
    ],
  },
];

/** Every department as one flat array, for validation and search. */
export const DEPARTMENTS = DEPARTMENT_GROUPS.flatMap((g) => g.items);

/** Case-insensitive membership test. */
const BY_LOWER = new Map(DEPARTMENTS.map((d) => [d.toLowerCase(), d]));

/**
 * The canonical spelling of a department, or null if it is not on the list.
 * Case- and whitespace-insensitive, so "  computer science and engineering "
 * resolves rather than being rejected for invisible differences.
 */
export const canonicalDepartment = (value) =>
  BY_LOWER.get(String(value ?? '').trim().toLowerCase()) ?? null;

export const isKnownDepartment = (value) => canonicalDepartment(value) !== null;
